# Generated by Django 4.1.3 on 2022-11-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='ыдшвук_css',
            new_name='slide_css',
        ),
    ]
