# Generated by Django 4.1.3 on 2022-11-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("slider", "0002_alter_slider_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slider",
            options={
                "verbose_name": "Front Image",
                "verbose_name_plural": "Front Image",
            },
        ),
        migrations.RemoveField(
            model_name="slider",
            name="slide_css",
        ),
    ]
