# Generated by Django 4.1.3 on 2022-11-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Мои Работы',
                'verbose_name_plural': 'Мои работы',
            },
        ),
    ]
