# Generated by Django 4.1.3 on 2022-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_photo",
                    models.ImageField(
                        max_length=200, upload_to="about/", verbose_name="photo"
                    ),
                ),
                ("ab_title", models.CharField(max_length=200, verbose_name="title")),
                ("ab_text", models.TextField(max_length=200, verbose_name="text")),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Commetns",
            },
        ),
    ]
