# Generated by Django 4.1.3 on 2022-11-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_subscribe',
            field=models.TextField(default='-', max_length=1000, null=True, verbose_name='Subscribes'),
        ),
    ]
