# Generated by Django 4.1.3 on 2022-11-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_order_order_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_subscribe',
        ),
        migrations.AddField(
            model_name='order',
            name='order_message',
            field=models.TextField(default='-', max_length=1000, null=True, verbose_name='message'),
        ),
    ]
