# Generated by Django 4.1.3 on 2022-11-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_remove_order_order_subscribe_order_order_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusCrm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Status_name",
                    models.CharField(max_length=200, verbose_name="Название статуса"),
                ),
            ],
            options={
                "verbose_name": "Статус",
                "verbose_name_plural": "Статусы",
            },
        ),
        migrations.CreateModel(
            name="CommentCrm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comment_text", models.TextField(verbose_name="Text comment")),
                (
                    "Comment_dt",
                    models.DateTimeField(auto_now=True, verbose_name="Create date"),
                ),
                (
                    "Comment_binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.order",
                        verbose_name="Comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Commetns",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm.statuscrm",
                verbose_name="Status",
            ),
        ),
    ]
