# Generated by Django 4.1.3 on 2022-11-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kategories", "0001_initial"),
        ("photoexp", "0004_delete_photoexp"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoExp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo_img",
                    models.ImageField(
                        max_length=200, upload_to="examples/", verbose_name="eximg"
                    ),
                ),
                ("name_img", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "category_ph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kategories.kategories",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Name",
                "verbose_name_plural": "Name",
            },
        ),
    ]
