# Generated by Django 4.1.3 on 2022-11-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photoexp", "0005_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photoexp",
            options={"verbose_name": "My gallery", "verbose_name_plural": "My gallery"},
        ),
    ]
